### ISSUE TITLE
EDA, FE

### ISSUE THREAD

**Issue by aseungbo** [aseungbo/TMDB-Box-office-Prediction#10]

**Comment by dodobrain** [comment]
영향을 많이 끼칠것이다:genre,cast, crew, production companies, original title, original_language, spoken_languages,



영향을 중간정도로 끼칠 것이다.
homepage, tagline, runtime(일정범위내), keywords, production countries
belongs_to_collection    

영향을 끼치지 않을 수도 있다: popularity


그 외 잘 모름: 
budget, overview, poster_path, release_date, status

**Comment by seungb5** [comment]
# 결측치 확인
# Counting NA in dataset

fig = plt.figure(figsize=(15, 10))
train.isna().sum().sort_values(ascending=True).plot(kind='barh',colors='Red', fontsize=20)

**Comment by 5oobin** [comment]
**예산과 수익은 연관이 있음**

import seaborn as sns
import matplotlib.pyplot as plt

sns.jointplot(x="budget", y="revenue", data=train, height=11, ratio=4, color="g")
plt.show()

**Comment by 5oobin** [comment]
**하지만 popularity와 수익은 연관이 없음**

sns.jointplot(x="popularity", y="revenue", data=train, height=11, ratio=4, color="g")
plt.show()

**Comment by 5oobin** [comment]
**runtime 2시간쯤이 수익과 관련이 있으나 영화 대부분이 2시간이라서 그런듯**

sns.jointplot(x="runtime", y="revenue", data=train, height=11, ratio=4, color="g")
plt.show()

**Comment by 5oobin** [comment]
**release date로 여러 데이터 살펴보기**

**1.  사전 준비**

import numpy as np

# 2/20/15로 되어있는 release date를 연도로 모으기
train[['release_month','release_day','release_year']]=train['release_date'].str.split('/',expand=True).replace(np.nan, -1).astype(int)
# 연도 끝 두자리수만 있기 때문에 앞에 19/20 붙이기
train.loc[ (train['release_year'] <= 19) & (train['release_year'] < 100), "release_year"] += 2000
train.loc[ (train['release_year'] > 19)  & (train['release_year'] < 100), "release_year"] += 1900

releaseDate = pd.to_datetime(train['release_date'])
train['release_dayofweek'] = releaseDate.dt.dayofweek
train['release_quarter'] = releaseDate.dt.quarter

**Comment by 5oobin** [comment]
**2. 연도별로 살펴보자**
#### 해가 갈수록 많은 영화가 개봉됨

plt.figure(figsize=(20,12))
sns.countplot(train['release_year'].sort_values())
plt.title("Movie Release count by Year",fontsize=20)
loc, labels = plt.xticks()
plt.xticks(fontsize=12,rotation=90)
plt.show()

**Comment by 5oobin** [comment]
3. 월별로 살펴보자
#### 연관이 있을지...?

sns.countplot(train['release_month'].sort_values())
plt.title("Release Month Count",fontsize=10)
loc, labels = plt.xticks()
loc, labels = loc, ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
plt.xticks(loc, labels,fontsize=10)
plt.show()

**Comment by 5oobin** [comment]
**4. 일별로 살펴보자**
#### 일별은 상관없는듯

sns.countplot(train['release_day'].sort_values())
plt.title("Release Day Count",fontsize=10)
plt.xticks(fontsize=10)
plt.show()

**Comment by 5oobin** [comment]
**5. 요일별로 살펴보자**
#### 금요일이 압도적으로 높음

sns.countplot(train['release_dayofweek'].sort_values())
plt.title("Total movies released on Day Of Week",fontsize=10)
loc, labels = plt.xticks()
loc, labels = loc, ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
plt.xticks(loc, labels,fontsize=10)
plt.show()

**Comment by 5oobin** [comment]
**6. 분기별로 살펴보자**
#### 상관이 있나?
sns.countplot(train['release_quarter'].sort_values())
plt.title("Total movies released in a quarter",fontsize=10)
plt.show()

**Comment by seungb5** [comment]
#### JSON dict 풀어내기

dict_columns = ['belongs_to_collection', 'genres', 'production_companies',
                'production_countries', 'spoken_languages', 'Keywords', 'cast', 'crew']

def text_to_dict(df):
    for column in dict_columns:
        df[column] = df[column].apply(lambda x: {} if pd.isna(x) else ast.literal_eval(x) )
    return df
        
train = text_to_dict(train)
test = text_to_dict(test)

**Comment by 5oobin** [comment]
**3. date 별 개봉 영화 수익 평균**

#### 연도별 수익: 점차 증가 추세
train['meanRevenueByYear'] = train.groupby("release_year")["revenue"].aggregate('mean')
train['meanRevenueByYear'].plot(figsize=(15,10),color="g")
plt.xticks(np.arange(1920,2018,4))
plt.xlabel("Release Year")
plt.ylabel("Revenue")
plt.title("Movie Mean Revenue By Year",fontsize=20)
plt.show()

#### 월별 수익: 5,6,7월, 연말에 증가
train['meanRevenueByMonth'] = train.groupby("release_month")["revenue"].aggregate('mean')
train['meanRevenueByMonth'].plot(color="g")
plt.xlabel("Release Month")
plt.ylabel("Revenue")
plt.title("Movie Mean Revenue Release Month",fontsize=10)
plt.show()

#### 요일별 수익: 월화수에 개봉한 영화가 수익이 확실히 높음
train['meanRevenueByDayOfWeek'] = train.groupby("release_dayofweek")["revenue"].aggregate('mean')
train['meanRevenueByDayOfWeek'].plot(color="g")
plt.xlabel("Day of Week")
plt.ylabel("Revenue")
plt.title("Movie Mean Revenue by Day of Week",fontsize=10)
plt.show()

#### 분기별 수익: 2, 4분기가 높음
train['meanRevenueByQuarter'] = train.groupby("release_quarter")["revenue"].aggregate('mean')
train['meanRevenueByQuarter'].plot(color="g")
plt.xticks(np.arange(1,5,1))
plt.xlabel("Quarter")
plt.ylabel("Revenue")
plt.title("Movie Mean Revenue by Quarter",fontsize=10)
plt.show()

**Comment by seungb5** [comment]
Seaborn 데이터 시각화
https://datascienceschool.net/view-notebook/4c2d5ff1caab4b21a708cc662137bc65/

**Comment by seungb5** [comment]
#### 범주형 데이터 전처리
train['collection_name'] = train['belongs_to_collection'].apply(lambda x: x[0]['name'] if x != {} else 0)
train['has_collection'] = train['belongs_to_collection'].apply(lambda x: len(x) if x != {} else 0)

test['collection_name'] = test['belongs_to_collection'].apply(lambda x: x[0]['name'] if x != {} else 0)
test['has_collection'] = test['belongs_to_collection'].apply(lambda x: len(x) if x != {} else 0)

train = train.drop(['belongs_to_collection'], axis=1)
test = test.drop(['belongs_to_collection'], axis=1)

**Comment by seungb5** [comment]
#### top_cast_names dummy 추가하기
top_cast_names = [m[0] for m in Counter([i for j in list_of_cast_names for i in j]).most_common(30)]
for g in top_cast_names:
    train['cast_name_' + g] = train['all_cast'].apply(lambda x: 1 if g in x else 0)

**Comment by 5oobin** [comment]
**개봉안했다는 4개의 영화모두 개봉했고 수익도 있음**

train.loc[train['status'] == "Rumored"][['title','status','revenue']]

**Comment by 5oobin** [comment]
**변수와 수익 연관성 살펴보기**

#### 1. 홈페이지 유무: 연관 있음 - 있으면 수익 높음
import seaborn as sns
import matplotlib.pyplot as plt

train['has_homepage'] = 1
train.loc[pd.isnull(train['homepage']) ,"has_homepage"] = 0
sns.catplot(x="has_homepage", y="revenue", data=train)
plt.title('Revenue of movies with and without homepage');

#### 2. 테그라인 유무: 연관 있음 - 있으면 수익 높음
train['isTaglineNA'] = 0
train.loc[pd.isnull(train['tagline']) ,"isTaglineNA"] = 1
sns.catplot(x="isTaglineNA", y="revenue", data=train)
plt.title('Revenue of movies with and without a tagline');

#### 3. 타이틀 동일 유무: 연관 있음 - 타이틀이 동일하면 수익 높음
train['isTitleDifferent'] = 1
train.loc[ train['original_title'] == train['title'] ,"isTitleDifferent"] = 0 
sns.catplot(x="isTitleDifferent", y="revenue", data=train)
plt.title('Revenue of movies with single and multiple titles');

#### 4. 언어: 연관 있음 - 영문이면 수익 높음
train['isOriginalLanguageEng'] = 0 
train.loc[ train['original_language'] == "en" ,"isOriginalLanguageEng"] = 1
sns.catplot(x="isOriginalLanguageEng", y="revenue", data=train)
plt.title('Revenue of movies when Original Language is English and Not English');

**Comment by dodobrain** [comment]
> #### 범주형 데이터 전처리
> def text_to_dict(df):
> for column in dict_columns:
> df[column] = df[column].apply(lambda x: {} if pd.isna(x) else ast.literal_eval(x) )
> return df
> 
> #### colletion
> train['collection_name'] = train['belongs_to_collection'].apply(lambda x: x[0]['name'] if x != {} else 0)
> train['has_collection'] = train['belongs_to_collection'].apply(lambda x: len(x) if x != {} else 0)
> 
> test['collection_name'] = test['belongs_to_collection'].apply(lambda x: x[0]['name'] if x != {} else 0)
> test['has_collection'] = test['belongs_to_collection'].apply(lambda x: len(x) if x != {} else 0)
> 
> train = train.drop(['belongs_to_collection'], axis=1)
> test = test.drop(['belongs_to_collection'], axis=1)
> 
> #### genres
> train['num_genres'] = train['genres'].apply(lambda x: len(x) if x != {} else 0)
> train['all_genres'] = train['genres'].apply(lambda x: ' '.join(sorted([i['name'] for i in x])) if x != {} else '')
> train = train.drop(['genres'], axis=1)
> test = test.drop(['genres'], axis=1)

> #### production_companies
>train['num_production_companies'] = train['production_companies'].apply(lambda x: len(x) if x != {} else >0)
>train['all_production_companies'] = train['production_companies'].apply(lambda x: ' >'.join(sorted([i['name'] for i in x])) if x != {} else '')
>train = train.drop(['production_companies'], axis=1)
>test = test.drop(['production_companies'], axis=1)

> #### production_countries
>train['num_production_countries'] = train['production_countries'].apply(lambda x: len(x) if x != {} else 0)
>train['all_production_countries'] = train['production_countries'].apply(lambda x: ' '.join(sorted([i['name'] >for i in x])) if x != {} else '')
>train = train.drop(['production_countries'], axis=1)
>test = test.drop(['production_countries'], axis=1)

**Comment by dada9140** [comment]
### budget_year_ratio 함수

test.loc[test.release_date.isna(), 'release_date'] = '05/01/00'

train['release_date'] = pd.to_datetime(train['release_date'], format='%m/%d/%y')
train['release_date_year'] = train.release_date.dt.year

test['release_date'] = pd.to_datetime(test['release_date'], format='%m/%d/%y')
test['release_date_year'] = test.release_date.dt.year

def new_features(df):
   
    df['_budget_year_ratio'] = df['budget'] / (df['release_date_year'] * df['release_date_year']) 
    
    return df

train = new_features(train)
test = new_features(test)

**Comment by 5oobin** [comment]
**Cast**

train['all_cast'] = train['cast'].apply(lambda x: sorted([i['name'] for i in x]) if x != {} else '')
test['all_cast'] = test['cast'].apply(lambda x: sorted([i['name'] for i in x]) if x != {} else '')



list_of_cast_names = list(train['cast'].apply(lambda x: [i['name'] for i in x] if x != {} else []).values)
top_cast_names = [m[0] for m in Counter([i for j in list_of_cast_names for i in j]).most_common(10)]

for g in top_cast_names:
    train['cast_name_' + g] = train['all_cast'].apply(lambda x: 1 if g in x else 0)

for g in top_cast_names:
    test['cast_name_' + g] = test['all_cast'].apply(lambda x: 1 if g in x else 0)



num_top_cast = []

for i in range(len(train.index)):
    names = set(train.all_cast[i])
    topnames = set(top_cast_names)
    num_top_cast.append(len(names&topnames))



train["num_top_cast"] = num_top_cast

**Comment by 5oobin** [comment]
**Crew**

train['all_crew'] = train['crew'].apply(lambda x: sorted([i['name'] for i in x]) if x != {} else '')
test['all_crew'] = test['crew'].apply(lambda x: sorted([i['name'] for i in x]) if x != {} else '')

list_of_crew_names = list(train['crew'].apply(lambda x: [i['name'] for i in x] if x != {} else []).values)
top_crew_names = [m[0] for m in Counter([i for j in list_of_crew_names for i in j]).most_common(10)]

for g in top_crew_names:
train['crew_name_' + g] = train['all_crew'].apply(lambda x: 1 if g in x else 0)

for g in top_crew_names:
test['crew_name_' + g] = test['all_crew'].apply(lambda x: 1 if g in x else 0)

num_top_crew = []

for i in range(len(train.index)):
names = set(train.all_crew[i])
topnames = set(top_crew_names)
num_top_crew.append(len(names&topnames))

train["num_top_crew"] = num_top_crew

**Comment by 5oobin** [comment]
![Production Countries US](https://user-images.githubusercontent.com/42176961/56793625-6223f080-6847-11e9-8228-b6fb2b979952.JPG)

**Comment by 5oobin** [comment]
![Spoken Language English](https://user-images.githubusercontent.com/42176961/56793655-710aa300-6847-11e9-9b6b-b615c65aebcc.JPG)
