### ISSUE TITLE
base model

### ISSUE THREAD

**Issue by aseungbo** [aseungbo/TMDB-Box-office-Prediction#11]
[base model 참고](https://www.kaggle.com/somang1418/eda-lgb-xgb-modelings-with-a-cute-panda-meme)

**Comment by seungb5** [comment]
![base model 결과](https://user-images.githubusercontent.com/46778769/56773931-61fe0380-67fb-11e9-9158-55a50158abe8.PNG)

**Comment by seungb5** [comment]
성능 개선 후 base model
![성능 개선 후 base model 결과](https://user-images.githubusercontent.com/46778769/56792592-efb21100-6844-11e9-92c6-b63bb3733fa1.PNG)

**Comment by seungb5** [comment]
XGBoost
![성능 개선 전 XGB 결과](https://user-images.githubusercontent.com/46778769/56793305-acf13880-6846-11e9-9b92-79f583fa2c92.PNG)
![성능 개선 후 XGB 결과](https://user-images.githubusercontent.com/46778769/56793306-acf13880-6846-11e9-81c9-c2e28d9aa5d7.PNG)
