### ISSUE TITLE
함수 정의

### ISSUE THREAD

**Issue by aseungbo** [aseungbo/TMDB-Box-office-Prediction#13]
데이터 전처리, 변환에 사용하는 함수들 모아 두기.

**Comment by seungb5** [comment]
### date_features
def date_features(df):
df[['release_month','release_day','release_year']]=df['release_date'].str.split('/',expand=True).replace(np.nan, -1).astype(int)
df.loc[ (train['release_year'] <= 19) & (df['release_year'] < 100), "release_year"] += 2000
df.loc[ (train['release_year'] > 19) & (df['release_year'] < 100), "release_year"] += 1900
return df

**Comment by seungb5** [comment]
#### text_to_dict
def text_to_dict(df):
    for column in dict_columns:
        df[column] = df[column].apply(lambda x: {} if pd.isna(x) else ast.literal_eval(x) )
    return df
